In [1]:
!pip install ydata-profiling scikit-learn pandas matplotlib seaborn

Collecting ydata-profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pandas
  Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting matplotlib
  Using cached matplotlib-3.7.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.7 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scipy<1.16,>=1.4.1 (from ydata-profiling)
  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
Requirement already satisfied: pydantic>=2 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from ydata-profiling) (2.10.6)
Collecting PyYAML<6.1,>=5.0.0 (from ydata-profiling)
  Downloading PyYAML-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from ydata-profiling) (3.1.5)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from ydata-profiling) (1.24.4)
Collecting htmlmin==0.1.12 (from ydata-profiling)
  Using cached htmlmin-0.1.12-py3-none-any.whl
Collecting phik<0.13,>=0.11.1 (from ydata-profiling)
  Using cached phik-0.12.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from ydata-profiling) (4.67.1)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Using cached multimethod-1.10-py3-none-any.whl.metadata (8.2 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling)
  Using cached statsmodels-0.14.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.5 kB)
Collecting typeguard<5,>=3 (from ydata-profiling)
  Using cached typeguard-4.4.0-py3-none-any.whl.metadata (3.8 kB)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Using cached ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting wordcloud>=1.9.3 (from ydata-profiling)
  Using cached wordcloud-1.9.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting dacite>=1.8 (from ydata-profiling)
  Using cached dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<=0.61,>=0.56.0 (from ydata-profiling)
  Using cached numba-0.58.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.7 kB)
Collecting PyWavelets (from imagehash==4.3.1->ydata-profiling)
  Using cached PyWavelets-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Requirement already satisfied: pillow in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from imagehash==4.3.1->ydata-profiling) (10.4.0)
Collecting joblib>=1.1.1 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.9 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.57.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (102 kB)
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Using cached kiwisolver-1.4.7-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from matplotlib) (24.2)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.1.4-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from matplotlib) (6.4.5)
Requirement already satisfied: zipp>=3.1.0 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.20.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Collecting llvmlite<0.42,>=0.41.0dev0 (from numba<=0.61,>=0.56.0->ydata-profiling)
  Using cached llvmlite-0.41.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: importlib-metadata in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (8.5.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: six>=1.5 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.1.31)
Collecting patsy>=0.5.4 (from statsmodels<1,>=0.13.2->ydata-profiling)
  Using cached patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: attrs>=19.3.0 in /home/ymarca/anaconda3/envs/openai/lib/python3.8/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.1.0)
Collecting networkx>=2.4 (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Using cached networkx-3.1-py3-none-any.whl.metadata (5.3 kB)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.29-py3-none-any.whl.metadata (5.8 kB)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Using cached scikit_learn-1.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.1 MB)
Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Using cached matplotlib-3.7.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading fonttools-4.57.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 10.4 MB/s eta 0:00:0031m11.4 MB/s eta 0:00:01
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached kiwisolver-1.4.7-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Using cached multimethod-1.10-py3-none-any.whl (9.9 kB)
Using cached numba-0.58.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
Using cached phik-0.12.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (686 kB)
Using cached pyparsing-3.1.4-py3-none-any.whl (104 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading PyYAML-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (746 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 746.5/746.5 kB 10.7 MB/s eta 0:00:00
Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Using cached statsmodels-0.14.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Using cached typeguard-4.4.0-py3-none-any.whl (35 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Using cached wordcloud-1.9.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (520 kB)
Using cached llvmlite-0.41.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.6 MB)
Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Using cached patsy-1.0.1-py2.py3-none-any.whl (232 kB)
Downloading puremagic-1.29-py3-none-any.whl (43 kB)
Using cached PyWavelets-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
Installing collected packages: pytz, puremagic, htmlmin, tzdata, threadpoolctl, scipy, PyYAML, PyWavelets, pyparsing, patsy, networkx, multimethod, llvmlite, kiwisolver, joblib, fonttools, dacite, cycler, contourpy, typeguard, scikit-learn, pandas, numba, matplotlib, imagehash, wordcloud, visions, statsmodels, seaborn, phik, ydata-profiling
Successfully installed PyWavelets-1.4.1 PyYAML-6.0.2 contourpy-1.1.1 cycler-0.12.1 dacite-1.9.2 fonttools-4.57.0 htmlmin-0.1.12 imagehash-4.3.1 joblib-1.4.2 kiwisolver-1.4.7 llvmlite-0.41.1 matplotlib-3.7.5 multimethod-1.10 networkx-3.1 numba-0.58.1 pandas-2.0.3 patsy-1.0.1 phik-0.12.4 puremagic-1.29 pyparsing-3.1.4 pytz-2025.2 scikit-learn-1.3.2 scipy-1.10.1 seaborn-0.13.2 statsmodels-0.14.1 threadpoolctl-3.5.0 typeguard-4.4.0 tzdata-2025.2 visions-0.8.1 wordcloud-1.9.4 ydata-profiling-4.16.1

In [2]:
import pandas as pd
from ydata_profiling import ProfileReport

# Load dataset
df = pd.read_csv('data/House Price India.csv')
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000

In [3]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     14620 non-null  int64
 1   Date                                   14620 non-null  int64
 2   number of bedrooms                     14620 non-null  int64
 3   number of bathrooms                    14620 non-null  float64
 4   living area                            14620 non-null  int64
 5   lot area                               14620 non-null  int64
 6   number of floors                       14620 non-null  float64
 7   waterfront present                     14620 non-null  int64
 8   number of views                        14620 non-null  int64
 9   condition of the house                 14620 non-null  int64
 10  grade of the house                     14620 non-null  int64
 11  Area of the house(excluding basement)  14620 non-null  int64
 12  Area of the basement                   14620 non-null  int64
 13  Built Year                             14620 non-null  int64
 14  Renovation Year                        14620 non-null  int64
 15  Postal Code                            14620 non-null  int64
 16  Lattitude                              14620 non-null  float64
 17  Longitude                              14620 non-null  float64
 18  living_area_renov                      14620 non-null  int64
 19  lot_area_renov                         14620 non-null  int64
 20  Number of schools nearby               14620 non-null  int64
 21  Distance from the airport              14620 non-null  int64
 22  Price                                  14620 non-null  int64
dtypes: float64(4), int64(19)
memory usage: 2.6 MB

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
count,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,...,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04
mean,6.762821e+09,42604.538646,3.379343,2.129583,2098.262996,1.509328e+04,1.502360,0.007661,0.233105,3.430506,...,1970.926402,90.924008,122033.062244,52.792848,-114.404007,1996.702257,12753.500068,2.012244,64.950958,5.389322e+05
std,6.237575e+03,67.347991,0.938719,0.769934,928.275721,3.791962e+04,0.540239,0.087193,0.766259,0.664151,...,29.493625,416.216661,19.082418,0.137522,0.141326,691.093366,26058.414467,0.817284,8.936008,3.675324e+05
min,6.762810e+09,42491.000000,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,...,1900.000000,0.000000,122003.000000,52.385900,-114.709000,460.000000,651.000000,1.000000,50.000000,7.800000e+04
25%,6.762815e+09,42546.000000,3.000000,1.750000,1440.000000,5.010750e+03,1.000000,0.000000,0.000000,3.000000,...,1951.000000,0.000000,122017.000000,52.707600,-114.519000,1490.000000,5097.750000,1.000000,57.000000,3.200000e+05
50%,6.762821e+09,42600.000000,3.000000,2.250000,1930.000000,7.620000e+03,1.500000,0.000000,0.000000,3.000000,...,1975.000000,0.000000,122032.000000,52.806400,-114.421000,1850.000000,7620.000000,2.000000,65.000000,4.500000e+05
75%,6.762826e+09,42662.000000,4.000000,2.500000,2570.000000,1.080000e+04,2.000000,0.000000,0.000000,4.000000,...,1997.000000,0.000000,122048.000000,52.908900,-114.315000,2380.000000,10125.000000,3.000000,73.000000,6.450000e+05
max,6.762832e+09,42734.000000,33.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,...,2015.000000,2015.000000,122072.000000,53.007600,-113.505000,6110.000000,560617.000000,3.000000,80.000000,7.700000e+06

In [5]:
profile = ProfileReport(df, title="India House Price Profiling", explorative=True)
profile.to_file("india_house_price_eda.html")

Summarize dataset:   0%|                   | 0/28 [00:00<?, ?it/s, Describe variable: number of bathrooms]
Summarize dataset:  25%|███         | 7/28 [00:00<00:00, 32.46it/s, Describe variable: grade of the house]
 22%|███████████████▏                                                      | 5/23 [00:00<00:00, 27.81it/s]
Summarize dataset:  57%|████████▌      | 16/28 [00:00<00:00, 30.57it/s, Describe variable: lot_area_renov]
Summarize dataset:  75%|██████████████████      | 21/28 [00:00<00:00, 35.55it/s, Describe variable: Price]
100%|█████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 39.41it/s]
Summarize dataset: 100%|█████████████████████████████████████| 393/393 [00:44<00:00,  8.82it/s, Completed]
Generate report structure: 100%|████████████████████████████████████████████| 1/1 [00:06<00:00,  6.34s/it]
Render HTML: 100%|██████████████████████████████████████████████████████████| 1/1 [00:10<00:00, 10.87s/it]
Export report to file: 100%|████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.83it/s]